// Copyright 2023 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package d2vm

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sirupsen/logrus"

	"go.linka.cloud/d2vm/pkg/exec"
)

const grubCfg = `GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=0
GRUB_CMDLINE_LINUX_DEFAULT="%s"
GRUB_CMDLINE_LINUX="root=LABEL=rootfs"
GRUB_TERMINAL=console
`

const grubCfgRhel = `GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_CMDLINE_LINUX="root=LABEL=rootfs %s"
GRUB_TERMINAL=console
GRUB_ENABLE_BLSCFG=false
GRUB_DISABLE_LINUX_UUID=true
`

type grubCommon struct {
	name string
	c    Config
	r    OSRelease
	root string
	dev  string
}

func isRhelFamily(r Release) bool {
	return r == ReleaseCentOS || r == ReleaseRocky || r == ReleaseAlmaLinux || r == ReleaseRHEL
}

func newGrubCommon(c Config, r OSRelease) *grubCommon {
	name := "grub"
	if isRhelFamily(r.ID) {
		name = "grub2"
	}
	return &grubCommon{
		name: name,
		c:    c,
		r:    r,
	}
}

func (g *grubCommon) prepare(ctx context.Context, dev, root, cmdline string) (clean func(), err error) {
	g.dev = dev
	g.root = root

	cfg := grubCfg
	if isRhelFamily(g.r.ID) {
		cfg = grubCfgRhel
	}
	if err = os.WriteFile(filepath.Join(root, "etc", "default", "grub"), []byte(fmt.Sprintf(cfg, cmdline)), perm); err != nil {
		return
	}

	if err = os.MkdirAll(filepath.Join(root, "boot", g.name), os.ModePerm); err != nil {
		return
	}
	mounts := []string{"dev", "proc", "sys"}
	var unmounts []string
	clean = func() {
		for _, v := range unmounts {
			if err := exec.Run(ctx, "umount", filepath.Join(root, v)); err != nil {
				logrus.Errorf("failed to unmount /%s: %s", v, err)
			}
		}
	}
	defer func() {
		if err != nil {
			clean()
		}
	}()
	for _, v := range mounts {
		if err = exec.Run(ctx, "mount", "-o", "bind", "/"+v, filepath.Join(root, v)); err != nil {
			return
		}
		unmounts = append(unmounts, v)
	}
	return
}

func (g *grubCommon) install(ctx context.Context, args ...string) error {
	if g.dev == "" || g.root == "" {
		return fmt.Errorf("grubCommon not prepared")
	}
	args = append([]string{g.root, g.name + "-install"}, args...)
	return exec.Run(ctx, "chroot", args...)
}

func (g *grubCommon) mkconfig(ctx context.Context) error {
	if g.dev == "" || g.root == "" {
		return fmt.Errorf("grubCommon not prepared")
	}
	if isRhelFamily(g.r.ID) {
		return g.mkconfigRhel(ctx)
	}
	return exec.Run(ctx, "chroot", g.root, g.name+"-mkconfig", "-o", "/boot/"+g.name+"/grub.cfg")
}

func (g *grubCommon) mkconfigRhel(ctx context.Context) error {
	// Find kernel and initrd
	kernelPattern := filepath.Join(g.root, "boot", "vmlinuz-*")
	matches, err := filepath.Glob(kernelPattern)
	if err != nil {
		return fmt.Errorf("failed to find kernel: %w", err)
	}
	if len(matches) == 0 {
		return fmt.Errorf("no kernel found in /boot")
	}
	// Pick the latest kernel
	kernel := matches[len(matches)-1]
	kernelName := filepath.Base(kernel)

	initrdPattern := filepath.Join(g.root, "boot", "initramfs-*.img")
	initrdMatches, err := filepath.Glob(initrdPattern)
	if err != nil {
		return fmt.Errorf("failed to find initrd: %w", err)
	}
	if len(initrdMatches) == 0 {
		return fmt.Errorf("no initrd found in /boot")
	}
	initrd := initrdMatches[len(initrdMatches)-1]
	initrdName := filepath.Base(initrd)

	// Extract version from kernel name
	version := strings.TrimPrefix(kernelName, "vmlinuz-")

	cfg := fmt.Sprintf(`# Generated by d2vm
set default="0"
set timeout=0

insmod part_msdos
insmod fat
search --no-floppy --label --set=root boot

menuentry 'Rocky Linux %s' --class gnu-linux --class gnu --class os {
    load_video
    insmod gzio
    linux /%s root=LABEL=rootfs ro net.ifnames=0 rootfstype=ext4 console=tty0 console=ttyS0,115200n8
    initrd /%s
}
`, version, kernelName, initrdName)

	return os.WriteFile(filepath.Join(g.root, "boot", g.name, "grub.cfg"), []byte(cfg), perm)
}
