site_name: ""
docs_dir: content
site_dir: build
edit_uri: edit/docs/docs/content/
theme:
  name: linka-cloud
  logo: assets/d2vm-light-tr.png
  favicon: assets/d2vm-favicon.png
  language: en
repo_url: https://github.com/linka-cloud/d2vm
copyright: Copyright &copy; 2022 Linka Cloud
nav:
- Getting Started: index.md
- Complete Example: full-example.md
- Command Line:
    - d2vm: reference/d2vm.md
    - build: reference/d2vm_build.md
    - convert: reference/d2vm_convert.md
    - run:
        - hetzner: reference/d2vm_run_hetzner.md
        - qemu: reference/d2vm_run_qemu.md
        - virtualbox: reference/d2vm_run_vbox.md
    - completion:
        - bash: reference/d2vm_completion_bash.md
        - fish: reference/d2vm_completion_fish.md
        - powershell: reference/d2vm_completion_powershell.md
        - zsh: reference/d2vm_completion_zsh.md
    - version: reference/d2vm_version.md

extra:
  homepage: https://github.com/linka-cloud/d2vm
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/linka-cloud
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/linkacloud

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tasklist

