site_name: ""
docs_dir: content
site_dir: build
theme:
  name: linka-cloud
  logo: assets/d2vm-light-tr.png
  favicon: assets/d2vm-favicon.png
  language: en
repo_url: https://github.com/linka-cloud/d2vm
copyright: Copyright &copy; 2022 Linka Cloud
extra:
  homepage: https://github.com/linka-cloud/d2vm
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/linka-cloud
    - icon: fontawesome/brands/docker 
      link: https://hub.docker.com/r/linkacloud

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tasklist

